### ISSUE TITLE
lint only changed or added files in pre-commit

### ISSUE THREAD

**Issue by zaro0508** [codingjoe/relint#6]
I would like to run this linter with pre-commit[1] and I only want to lint changed or newly added files.  Is there a way to do that with the pre-commit framework? 

[1] https://pre-commit.com

**Comment by codingjoe** [comment]
Hi @zaro0508 that is a very good question. In fact @anapaulagomes contributed that feature a while ago. There is a catch, it isn't too easy to setup. This is mainly because pre-commit only provides each hook with a list of filenames rather than the diff. BUT we there is help:
1. install relint
2. copy [relint-pre-commit.sh](relint-pre-commit.sh)
3. Change your commit hook to:
    ```python
    -   id: relint
        name: relint
        entry: relint-pre-commit.sh
        language: system
```
